name: Build
on: [push, pull_request, merge_group]
jobs:
  build:
    strategy:
      matrix:
        java: [17-jdk, 20-jdk]
    runs-on: ubuntu-22.04
    container:
      image: eclipse-temurin:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-excludes: |
            gradle.properties
      - name: Setup gradle.properties
        env:
          GRADLE_PROPERTIES: ${{ vars.GRADLE_PROPERTIES }}
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
          echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties
      - name: Create placeholder assets dir
        run: mkdir -p ${{ env.GRADLE_USER_HOME }}/caches/fabric-loom/assets
      - run: ./gradlew check build publishToMavenLocal --stacktrace
      - uses: Juuxel/publish-checkstyle-report@v1
        if: ${{ failure() }}
        with:
          reports: |
            **/build/reports/checkstyle/*.xml
      - uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/
      - uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: ./*/build/libs/
      - uses: actions/upload-artifact@v3
        with:
          name: Maven Local
          path: /root/.m2/repository

#  client_test:
#    runs-on: ubuntu-22.04
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#      - uses: actions/setup-java@v3
#        with:
#          distribution: 'microsoft'
#          java-version: '17'
#      - name: Run Auto test Client
#        uses: modmuss50/xvfb-action@v1
#        with:
#          run: ./gradlew runProductionAutoTestClient --stacktrace --warning-mode=fail
#      - uses: actions/upload-artifact@v3
#        if: always()
#        with:
#          name: Test Screenshots
#          path: run/screenshots

#  server_test:
#    runs-on: ubuntu-22.04
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#      - uses: actions/setup-java@v3
#        with:
#          distribution: 'microsoft'
#          java-version: '17'
#      - run: mkdir run && echo "eula=true" >> run/eula.txt
#      - run: ./gradlew runProductionAutoTestServer --stacktrace --warning-mode=fail

  check_resources:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-excludes: |
            gradle.properties
      - name: Setup gradle.properties
        env:
          GRADLE_PROPERTIES: ${{ vars.GRADLE_PROPERTIES }}
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
          echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties
      - name: Create placeholder assets dir
        run: mkdir -p ${{ env.GRADLE_USER_HOME }}/caches/fabric-loom/assets
      - run: ./gradlew generateResources --stacktrace
      - run: if [ -n "$(git status --porcelain)" ]; then exit 1; fi
