name: Release
on: [workflow_dispatch] # Manual trigger

permissions:
  actions: read
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: eclipse-temurin:20-jdk
      options: --user root
    steps:
      - run: apt update && apt install git -y && git --version
      - run: git config --global --add safe.directory /__w/ForgifiedFabricAPI/ForgifiedFabricAPI
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: FabricMC/fabric-action-scripts@v2
        id: changelog
        with:
          context: changelog
          workflow_id: release.yml
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-excludes: |
            gradle.properties
      - name: Setup gradle.properties
        env:
          GRADLE_PROPERTIES: ${{ vars.GRADLE_PROPERTIES }}
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
          echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties
      - name: Create placeholder assets dir
        run: mkdir -p ${{ env.GRADLE_USER_HOME }}/caches/fabric-loom/assets
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew checkVersion build publish github --stacktrace
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
          SIGNING_SERVER: ${{ secrets.SIGNING_SERVER }}
          SIGNING_PGP_KEY: ${{ secrets.SIGNING_PGP_KEY }}
          SIGNING_JAR_KEY: ${{ secrets.SIGNING_JAR_KEY }}
